/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ParentViewRouteImport } from './routes/parent-view'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddTaskRouteImport } from './routes/add-task'
import { Route as IndexRouteImport } from './routes/index'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentViewRoute = ParentViewRouteImport.update({
  id: '/parent-view',
  path: '/parent-view',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddTaskRoute = AddTaskRouteImport.update({
  id: '/add-task',
  path: '/add-task',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-task': typeof AddTaskRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/parent-view': typeof ParentViewRoute
  '/profile': typeof ProfileRoute
  '/status': typeof StatusRoute
  '/update-password': typeof UpdatePasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-task': typeof AddTaskRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/parent-view': typeof ParentViewRoute
  '/profile': typeof ProfileRoute
  '/status': typeof StatusRoute
  '/update-password': typeof UpdatePasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-task': typeof AddTaskRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/parent-view': typeof ParentViewRoute
  '/profile': typeof ProfileRoute
  '/status': typeof StatusRoute
  '/update-password': typeof UpdatePasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-task'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/parent-view'
    | '/profile'
    | '/status'
    | '/update-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-task'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/parent-view'
    | '/profile'
    | '/status'
    | '/update-password'
  id:
    | '__root__'
    | '/'
    | '/add-task'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/parent-view'
    | '/profile'
    | '/status'
    | '/update-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddTaskRoute: typeof AddTaskRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  ParentViewRoute: typeof ParentViewRoute
  ProfileRoute: typeof ProfileRoute
  StatusRoute: typeof StatusRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-view': {
      id: '/parent-view'
      path: '/parent-view'
      fullPath: '/parent-view'
      preLoaderRoute: typeof ParentViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-task': {
      id: '/add-task'
      path: '/add-task'
      fullPath: '/add-task'
      preLoaderRoute: typeof AddTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddTaskRoute: AddTaskRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  ParentViewRoute: ParentViewRoute,
  ProfileRoute: ProfileRoute,
  StatusRoute: StatusRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
